language: cpp

env:
  matrix:
   - CRASH_PLEASE=boooooooom
   - HAPPY_NO_CRASH=all-good

compiler:
 # gcc compiler, clang would be fine too
 - gcc

before_install:
 # install the gnu debugger for later use in reading the core file
 - sudo apt-get -y install gdb

install:
 # What is the current file size max for core files?
 # It is usually 0, which means no core file will be dumped if there is a crash
 - ulimit -c
 - cat /proc/sys/kernel/core_pattern
 - sysctl kernel.core_pattern

before_script:
 # Set the core file limit to unlimited so a core file is generated upon crash
 - ulimit -c unlimited -S

script:
 - bash -v script.sh